const stockOutConfig = {

    "B9iwoJzkJmt": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "GMDZCHfIG5R": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "HGWi2hv4QTF": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "IY45Mrg2667": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "IhOFvWrEQOS": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "Ndyc3bzyPv5": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "SF2Sin2B9Rt": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "TNgVcvqbeGU": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "UJs4440jSZR": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "XoSkhx7Lap2": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "ZWiog7hr614": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "ZXINKn05Kx4": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "cDS8FxRpGId": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "e4OnA6SvieR": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "eIMRtBnup4u": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "lR4NkJEcUkb": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "oMT13k4O0Nj": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "onLrEIjlso0": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "pkXq7z8sOmJ": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "q1d19QGSLCt": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "t60jVZgtwxp": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "ukp4DzyLWXz": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "wyBwSsDuo1g": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "zIctIyuU21L": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
    "zas86QcEyOY": {
        Commodities_Client: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Commodities_Facilities: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        },
        Visits: {
            governmentHealth: "",
            ngo: "",
            otherSector: "",
            pharmacy: "",
            privateHospital: "",
            reporting: "",
            shopChurchFriend: "",
            type: "",
        }
    },
}