const stockOutConfig = {
  stockOut: {
    indicator_1: {
      locArr: [],
      methods: [],
      initialYear: "2011",
      finalYear: "",
      backTrackedYearMonth: "",
      backTrackingMonth: 1,
      stockOutType: "type_1",
      repoRate: [
        {
          de: [],
          name: "Actual Report",
          deName: "indicator_1_IND Method",
          selectedDE: [
            {
              id: "QyAR2wRndOh.HllvX50cXC0",
              displayName: "tr_stock_out_condom default",
            },
          ],
          type: "data_element",
          static_name: "Actual Report",
        },
      ],
      numNameCount: "",
      opDE: "",
      denomNameCount: "",
      opDE_name: "",
      numNameCount_name: "",
      denomNameCount_name: "",
      methodKey: "",
      numNameCount_ID: "",
      opDE_ID: "",
      denomNameCount_ID: "",
      frequency: [],
    },
    indicator_2: {
      locArr: [],
      numNameCount: "",
      opDE: "",
      denomNameCount: "",
      numNameCount_ID: "",
      opDE_ID: "",
      denomNameCount_ID: "",
      opDE_name: "",
      numNameCount_name: "",
      denomNameCount_name: "",
      methodKey: "",
      methods: [
        {
          de: [],
          name: "CycleBeads",
          selectedDE: [],
          type: "data_element",
          static_name: "CycleBeads",
        },
        {
          de: [],
          name: "IUD (10yr, 5yr)",
          selectedDE: [],
          type: "data_element",
          static_name: "IUD (10yr, 5yr)",
        },
        {
          de: [],
          name: "Implants (Implanon NXT, Jadelle)",
          selectedDE: [],
          type: "data_element",
          static_name: "Implants (Implanon NXT, Jadelle)",
        },
        {
          de: [],
          name: "Injectables",
          selectedDE: [],
          type: "data_element",
          static_name: "Injectables",
        },
        {
          de: [],
          name: "EC",
          selectedDE: [],
          type: "data_element",
          static_name: "EC",
        },
        {
          de: [],
          name: "Oral Pills (COC, POP)",
          selectedDE: [],
          type: "data_element",
          static_name: "Oral Pills (COC, POP)",
        },
        {
          de: [],
          name: "Condoms: female",
          selectedDE: [],
          type: "data_element",
          static_name: "Condoms: female",
        },
        {
          de: [],
          name: "Condoms: male",
          selectedDE: [],
          type: "data_element",
          static_name: "Condoms: male",
        },
        {
          de: [],
          name: "Spermicide",
          selectedDE: [],
          type: "data_element",
          static_name: "Spermicide",
        },
      ],
      frequency: [],
    },
    indicator_3: {
      locArr: [],
      numNameCount: "",
      opDE: "",
      denomNameCount: "",

      numNameCount_ID: "",
      opDE_ID: "",
      denomNameCount_ID: "",
      frequency: [],
      opDE_name: "",
      numNameCount_name: "",
      denomNameCount_name: "",
      methodKey: "",
      methods: [
        {
          de: [],
          name: "Any New Youth Acceptors",
          selectedDE: [],
          type: "data_element",
          static_name: "Any New Youth Acceptors",
        },
      ],
    },
    indicator_4: {
      locArr: [],
      numNameCount: "",
      opDE: "",
      denomNameCount: "",

      numNameCount_ID: "",
      opDE_ID: "",
      denomNameCount_ID: "",
      opDE_name: "",
      numNameCount_name: "",
      denomNameCount_name: "",
      methodKey: "",
      methods: [
        {
          de: [],
          name: "CycleBeads",
          selectedDE: [],
          type: "data_element",
          static_name: "CycleBeads",
        },
        {
          de: [],
          name: "IUD",
          selectedDE: [],
          type: "data_element",
          static_name: "IUD",
        },
        {
          de: [],
          name: "Implants",
          selectedDE: [],
          type: "data_element",
          static_name: "Implants",
        },
        {
          de: [],
          name: "Injectables",
          selectedDE: [],
          type: "data_element",
          static_name: "Injectables",
        },
        {
          de: [],
          name: "EC",
          selectedDE: [],
          type: "data_element",
          static_name: "EC",
        },
        {
          de: [],
          name: "Oral Pills",
          selectedDE: [],
          type: "data_element",
          static_name: "Oral Pills",
        },
        {
          de: [],
          name: "Condoms: female",
          selectedDE: [],
          type: "data_element",
          static_name: "Condoms: female",
        },
        {
          de: [],
          name: "Condoms: male",
          selectedDE: [],
          type: "data_element",
          static_name: "Condoms: male",
        },
        {
          de: [],
          name: "Spermicide",
          selectedDE: [],
          type: "data_element",
          static_name: "Spermicide",
        },
      ],
      frequency: [],
    },
  },
};

export default stockOutConfig;
